### ISSUE TITLE
Debug information

### ISSUE THREAD

**Issue by CyberParadise** [bogdanfinn/tls-client-api#4]
Can I somehow get more information about the request in the console, what are the headers, body? "withDebug": True in the request doesn't give me that kind of information

upd:
i use ubuntu
I use a binary file from the dist folder

**Comment by CyberParadise** [comment]
Can I somehow get more information about the request in the console, what are the headers, body? `"withDebug": True` in the request doesn't give me that kind of information

**Comment by bogdanfinn** [comment]
@CyberParadise please feel free to comment here a list of information you would be interested in to get logged while having debug to true.

Then i can easily implement that in the next release.

**Comment by CyberParadise** [comment]
> @CyberParadise please feel free to comment here a list of information you would be interested in to get logged while having debug to true.
> 
> Then i can easily implement that in the next release.

When debugging, in the terminal, I would like to see information such as:
  - Request address (already available)
  - Request headers
  - Request body (if any)
and:
  - Response status (already available)
  - Response headers
  - Response body

And if possible, then ja3 and its hash

**Comment by bogdanfinn** [comment]
@CyberParadise all the information mentioned above from you (except ja3 and hash) should be added to the latest versions.
