### ISSUE TITLE
Adding Cookies to CookieJar

### ISSUE THREAD

**Issue by killcod3** [bogdanfinn/tls-client-api#7]
"requestCookies" payload is apparently adding cookies at request level only. how we we append existing cookieJar?

**Comment by bogdanfinn** [comment]
@killcod3 requestCookies are added to the cookieJar see here: https://github.com/bogdanfinn/tls-client-api/blob/master/internal/tls-client-api/api/forward-request-handler.go#L54

maybe you can give some more information and some payloads to reproduce your issue? 

do you have the cookiejar disabled maybe? 
do you maybe add/check under the wrong URL ?

Without further information its hard to help you.
